      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          flavor: |
            latest=true
          images: europe-west3-docker.pkg.dev/tfl-prod-ea3b/tfl-docker/tumai-intro-rl
          tags: |
            type=sha
