name: Build docker image with the presentation

on:
  push:
    branches: [master]
  workflow_dispatch:
    inputs:
      reason:
        description: Why did you need to rebuild the image?
        required: False
        default: Image built from master was outdated


jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 0
          lfs: true
          persist-credentials: false
      # lfs=true is not enough, see https://stackoverflow.com/questions/61463578/github-actions-actions-checkoutv2-lfs-true-flag-not-converting-pointers-to-act
      - name: Pull LFS Objects
        run: git lfs pull
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GAR
        uses: docker/login-action@v1
        with:
          registry: europe-west3-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}
